apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-by-http
  labels:
    app: analysis-by-http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis-by-http
  template:
    metadata:
      labels:
        app: analysis-by-http
    spec:
      containers:
      - name: helloworld
        image: gcr.io/kapetanios/pipecd-helloworld:v0.0.2-81-g387c932
        args:
          - server
        ports:
        - containerPort: 9085
