apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-steps-canary
  labels:
    app: multi-steps-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-steps-canary
  template:
    metadata:
      labels:
        app: multi-steps-canary
    spec:
      containers:
      - name: helloworld
        image: gcr.io/kapetanios/pipecd-helloworld:v0.0.2-27-g067c7e0
        args:
          - server
        ports:
        - containerPort: 9085
