apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-by-config-change
  labels:
    app: canary-by-config-change
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-by-config-change
  template:
    metadata:
      labels:
        app: canary-by-config-change
    spec:
      containers:
        - name: helloworld
          image: gcr.io/pipecd/helloworld:v0.1.0-81-gfb72d89
          args:
            - server
          ports:
            - containerPort: 9085
          volumeMounts:
            - name: config
              mountPath: /etc/pipecd-config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: canary-by-config-change
